@startuml
|Passageiro|
start
:Abrir aplicativo;
if (Opção: Chamar veículo para local atual?) then (Sim)
  :Informar localização atual;
else (Não)
  :Informar localizaçao de origem desejada;
endif
:Informar destino desejado;
:Enviar solicitação de corrida;
|Motorista|
if (Receber solicitações de corrida?) then (Sim)
  :Receber notificação da solicitação;
  :Analisar detalhes da corrida;
  if (Aceitar corrida?) then (Sim)
    :Confirmar aceitação;
    |Passageiro|
    :Receber confirmação de corrida;
  else (Não)
    |Motorista|
    :Rejeitar corrida;
    :Aguardar próxima solicitação;
  endif
endif
|Passageiro|
:Esperar pela chegada do veículo;
|Motorista|
:Dirigir até o local do passageiro;
|Passageiro|
:Entrar no veículo;
:Iniciar a viagem;
|Motorista|
:Dirigir até o destino;
|Passageiro|
:Chegar ao destino;
:Encerrar a viagem;
|Motorista|
:Confirmar encerramento da viagem;
stop
@enduml