@startuml
class usuario {
- id: int
- senha: String 
- cadastroAprovado: String
- cpf : String
- nome : String
- sexo : char
- email: String
- data_nascimento : date
- telefone: string
- endereco: Endereco 
- dataCriacao : date
}
class Solicitacao {
- id: int
- clienteld: int
- horaPedido: time
- enderecoOrigem:Endereco 
- enderecoDestino: Endereco 
- statusSolicitacao: char
- metodoPag: char
}


class Corrida {
- id: int
- horaAceite : time
- motoristald: int
- distancia: float
- valor: float
- status : char
}

class motorista
{
- CNH : string
- Receber_corrida : string
}
class passageiro
{
- meioPagamento: MeioPagamento
}

class endereco
{
- cep: string
- rua: String
- numero: int
- Complemento: String
}

class MeioPagamento{
- bandeira_cartão : string
- numero : String
- validade: date
- cod_Verificacao: int
}

passageiro "1" *-up-x "0..*" MeioPagamento
passageiro "1" *-up-x "1" endereco
motorista "1" *-up-x "1" endereco
usuario "1" <|-down- "1" motorista
usuario "1" <|-right- "1" passageiro

passageiro --> Solicitacao
motorista --> Corrida
Solicitacao --* Corrida
@enduml