@startuml
actor      Passageiro       as user
boundary   "Tela Cadastro"    as tela
control     "Controlador De Cadastro " as ctrl
database    Database    as BD
participant "API Cadastro" as api

user -> tela : 1.cadastro
tela -> user : 1.1formulario
user -> tela : 2 formulario preenchido
tela -> ctrl : 2.1 (nome:string,email:string,senha:string,cpf:string,fotos:Img,endereco:Endereco)
ctrl -> BD : 2.2 Verifica_disponiblidade(cpf:string,email:string)
BD -> ctrl : 2.3 Resposta da disponibilidade(msg:string)
alt email e cpf em uso
ctrl -> tela: 2.4  "Email e cpf já utilizados"
tela -> user: 2.4.1  "Email e cpf já utilizados"
user -> tela: 2.5 fornece outro email e cpf
else email em uso
ctrl -> tela : 2.4  "email em uso"
tela -> user : 2.4.1  "email em uso"
user -> tela: 2.5 fornece outro email
else cpf em uso
ctrl -> tela : 2.4  "cpf em uso" 
tela -> user : 2.4.1  "cpf em uso" 
user -> tela: 2.5 fornece outro cpf
else emial e cpf não utilizados 
ctrl ->ctrl : 2.4  "OK"
end
ctrl -> BD : 2.4 SalvaDados(nome:string,email:string,senha:string,cpf:string,fotos:Img,endereco:Endereco)
ctrl -> api : 2.5 ValidaUsuario(cpf:string,fotos:Img)
alt não confirma identidade
api -> ctrl : "NOK"
ctrl -> tela : "A identidade não pode ser confirmada envie outra foto"
tela -> user : "A identidade não pode ser confirmada envie outra foto"
user -> tela : "nova foto"

else confrima a identidade
api -> ctrl : "OK"
ctrl -> tela : "Cadastro finalizado"
tela -> user : "Cadastro finalizado"
end
@enduml