@startuml
actor Usuário as U
participant "Página de Suporte" as P
participant Suporte as S
participant Atendente as A

U -> P: Abrir página de suporte
U -> P: Enviar mensagem
P -> S: Enviar mensagem
S -> A: encaminharMensagem(mensagem: str)
A -> S: enviarResposta(resposta: str)
S -> P: exibirResposta()
P -> U: Ler a resposta
@enduml